## Numpy

In [3]:
import numpy as np

In [4]:
list_to_convert = [1,2,3]

numpy_array = np.array(list_to_convert)

numpy_array

array([1, 2, 3])

In [11]:
a = [1,2,3,4,5]

a_numpy = np.array(a)

a_numpy.shape

(5,)

In [13]:
row_vector = a_numpy[:,np.newaxis] 
row_vector.shape

(5, 1)

In [14]:
col_vector = a_numpy[np.newaxis,:]  
col_vector.shape 

(1, 5)

In [15]:
a = range(0,15)
a_numpy = np.array(a)
b = a_numpy.reshape(3,5)  
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

3. Coverting any data type to Numpy array

In [16]:
a = [(1,2), [3,4,5], (6,7,8)]
b = np.asarray(a)
b

array([(1, 2), list([3, 4, 5]), (6, 7, 8)], dtype=object)

4. Get an n-dimensional Array of Zeros

In [23]:
a = np.zeros((3,4), dtype = np.float16)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

5. Get an n-dimensional Array of Ones

In [24]:
a = np.ones((3,4), dtype = np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

6. np.full and np.empty

In [25]:
a = np.full((2,3), 1, dtype=np.float16)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [26]:
a = np.empty((2,2),dtype=np.int16)
a 

array([[    0,     0],
       [16384, 16527]], dtype=int16)

7. Getting an Array of Evenly Spaced Values

In [30]:
np.linspace(1,2,num=5,endpoint=True,retstep=True)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

np.arange(1,10,2)

In [33]:
print(a)

a.shape

[[    0     0]
 [16384 16527]]


(2, 2)

9. Knowing the Dimensions of the NumPy Array

In [35]:
x = np.array([1,2,3])
x.ndim

1

10. Finding the Number of Elements in the NumPy Array

In [39]:
x = np.ones((3,2,4),dtype=np.int16)
print(x)
x.size

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


24

12. Finding the Data Type of Elements in the NumPy Array

In [40]:
x = np.ones((2,3), dtype=np.int16)
x.dtype

dtype('int16')

13. How to Create a Copy of NumPy Array

In [42]:
y = np.array([[1,3],[5,6]])
y

array([[1, 3],
       [5, 6]])

In [43]:
x=np.copy(y)
x

array([[1, 3],
       [5, 6]])

In [44]:
x.ndim

2

In [45]:
x[0, 0] = 1000
x 

array([[1000,    3],
       [   5,    6]])

In [46]:
y

array([[1, 3],
       [5, 6]])

14. Get Transpose of an n-d Array

In [47]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [48]:
x.T

array([[1, 3],
       [2, 4]])

15. Flatten an n-d Array to get a One-dimensional Array

In [49]:
x.reshape(-1)

array([1, 2, 3, 4])

In [50]:
x.ravel()

array([1, 2, 3, 4])

16. Change Axes of an n-d Array or Swap Dimensions

In [52]:
x = np.ones((3,4,5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [55]:
np.moveaxis(x,[1,2],[0,-2])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
x = np.array([[1,2],[3,4]])
x.shape

(2, 2)

In [57]:
np.swapaxes(x,0,1)

array([[1, 3],
       [2, 4]])

17. Convert NumPy Array to List

In [58]:
x = np.array([[3,4,5,9],[2,6,8,0]])
y = x.tolist()

In [59]:
y

[[3, 4, 5, 9], [2, 6, 8, 0]]

In [60]:
x

array([[3, 4, 5, 9],
       [2, 6, 8, 0]])

18. Change the Data Type of Elements in the NumPy Array

In [61]:
x = np.array([0,1,2.0,3.0,4.2],dtype=np.float32)
x

array([0. , 1. , 2. , 3. , 4.2], dtype=float32)

In [62]:
x.astype(np.int16)

array([0, 1, 2, 3, 4], dtype=int16)

In [64]:
x.astype(np.bool)

array([False,  True,  True,  True,  True])

19. Get Indices of Non-zero Elements

In [65]:
x = np.array([0,1,2.0,3.0,4.2],dtype=np.float32)
x.nonzero()

(array([1, 2, 3, 4], dtype=int64),)

In [67]:
x = np.array([[0,1],[3,5]])
x.nonzero()

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

20. Sort NumPy Array

In [75]:
x = np.array([[4,3],[3,2]])
x

array([[4, 3],
       [3, 2]])

In [76]:
x.sort(axis=0)
x

array([[3, 2],
       [4, 3]])

In [77]:
x.sort(axis=1)
x

array([[2, 3],
       [3, 4]])

21. Compare NumPy Arrays to Values

In [80]:
x = np.array([[0,1],[2,3]])
x==1

array([[False,  True],
       [False, False]])

In [81]:
(x == 1).astype(np.int16).sum()

1

22. Multiply Two NumPy Matrices

In [79]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [82]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [83]:
np.matmul(a,b)

array([[1., 2.],
       [3., 4.]])

In [84]:
np.multiply(a,b)

array([[1., 0.],
       [0., 4.]])

23. Dot Product of Two Arrays

In [85]:
a = np.array([[1,2,3],[4,8,16]])
a

array([[ 1,  2,  3],
       [ 4,  8, 16]])

In [87]:
b = np.array([5,6,11]).reshape(-1,1)
b

array([[ 5],
       [ 6],
       [11]])

In [88]:
np.dot(a,b)

array([[ 50],
       [244]])

24. Get Cross-product of Two NumPy Vectors

In [89]:
x = [1,2,3]
y = [4,5,6]
z = np.cross(x, y)
z 

array([-3,  6, -3])

25. Getting Gradient of an Array

In [90]:
x = np.array([5, 10, 14, 17, 19, 26], dtype=np.float16)
np.gradient(x)

array([5. , 4.5, 3.5, 2.5, 4.5, 7. ], dtype=float16)

26. How to Slice NumPy Array

In [91]:
x = np.array([[2,4,9],[3,1,5],[7,8,0]])
x 

array([[2, 4, 9],
       [3, 1, 5],
       [7, 8, 0]])

In [92]:
x[1,2]

5

In [93]:
x[[0,0,2,2],[0,1,0,1]] #List of rows and columns

array([2, 4, 7, 8])

In [94]:
x[[0,2],0:2]

array([[2, 4],
       [7, 8]])

27. Broadcasting

In [95]:
a = np.array([[3,5,8],[4,5,6],[9,7,2]])
a

array([[3, 5, 8],
       [4, 5, 6],
       [9, 7, 2]])

In [96]:
b = np.array([2,3,4]) # corrected
b

array([2, 3, 4])

In [97]:
a.shape

(3, 3)

In [98]:
b.shape


(3,)

In [99]:
np.array([[2,3,4], [2,3,4], [2,3,4]])

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [100]:
a + b

array([[ 5,  8, 12],
       [ 6,  8, 10],
       [11, 10,  6]])

## Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_1 = pd.read_csv("imdb_ratings.csv")
df_1.head()

Votes  Rank                       Title  Year  Decade
0   88355   8.4                    M (1931)  1931    1930
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980

In [3]:
df_1 = df_1.reindex(index=np.arange(1, df_1.shape[0], 1))
df_1.head()

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

2. How to create a data frame using a dictionary of pre-existing columns or NumPy 2D arrays?

In [5]:
dic_1 = {'states': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002, 2003],
         'pop': [1.5, .17, 3.6, 2.4, 2.9, 3.2]} 
dic_1

{'states': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 0.17, 3.6, 2.4, 2.9, 3.2]}

In [6]:
df_2 = pd.DataFrame(data=dic_1)
df_2

states  year   pop
0    Ohio  2000  1.50
1    Ohio  2001  0.17
2    Ohio  2002  3.60
3  Nevada  2001  2.40
4  Nevada  2002  2.90
5  Nevada  2003  3.20

Using NumPy Arrays

In [31]:
np_data_1 = np.array([[6, 7.5, 8], [0, 1, 2.0], [4, 2, 6]])
np_data_1

array([[6. , 7.5, 8. ],
       [0. , 1. , 2. ],
       [4. , 2. , 6. ]])

In [32]:
col_names = ['Joe', 'Ben', 'Ann']

In [33]:
df_3 = pd.DataFrame(data=np_data_1, columns=col_names)
df_3

Joe  Ben  Ann
0  6.0  7.5  8.0
1  0.0  1.0  2.0
2  4.0  2.0  6.0

3. How to visualize the top and bottom x values in a data frame?

In [34]:
df_1.head()

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [35]:
df_1.head(10) #will display top 10

Votes  Rank                         Title  Year  Decade
1   132823   8.3    Singin' in the Rain (1952)  1952    1950
2    74178   8.3          All About Eve (1950)  1950    1950
3   635139   8.6                   Léon (1994)  1994    1990
4   145514   8.2       The Elephant Man (1980)  1980    1980
5   425461   8.3      Full Metal Jacket (1987)  1987    1980
6   441174   8.1              Gone Girl (2014)  2014    2010
7   850601   8.3          Batman Begins (2005)  2005    2000
8    37664   8.2  Judgment at Nuremberg (1961)  1961    1960
9    46987   8.0       Relatos salvajes (2014)  2014    2010
10   56842   8.1  It Happened One Night (1934)  1934    1930

In [36]:
df_1.tail(10) #will display bottom 10

Votes  Rank                                         Title  Year  Decade
240   117590   8.4                     The Great Dictator (1940)  1940    1940
241    85012   8.1                   Strangers on a Train (1951)  1951    1950
242   476501   8.6                         Cidade de Deus (2002)  2002    2000
243   268905   8.4                           Citizen Kane (1941)  1941    1940
244    69988   8.1                                     8½ (1963)  1963    1960
245  1078416   8.7                           Forrest Gump (1994)  1994    1990
246    31003   8.1                  Le salaire de la peur (1953)  1953    1950
247   167076   8.2                               3 Idiots (2009)  2009    2000
248    91689   8.1                                Network (1976)  1976    1970
249   589477   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004    2000

In [37]:
cols_1 = ['Rank', 'Title']
df_1[cols_1].head(10)

Rank                         Title
1    8.3    Singin' in the Rain (1952)
2    8.3          All About Eve (1950)
3    8.6                   Léon (1994)
4    8.2       The Elephant Man (1980)
5    8.3      Full Metal Jacket (1987)
6    8.1              Gone Girl (2014)
7    8.3          Batman Begins (2005)
8    8.2  Judgment at Nuremberg (1961)
9    8.0       Relatos salvajes (2014)
10   8.1  It Happened One Night (1934)

In [38]:
cols_1 = ['Rank', 'Title']
df_1[cols_1].head(10)

Rank                         Title
1    8.3    Singin' in the Rain (1952)
2    8.3          All About Eve (1950)
3    8.6                   Léon (1994)
4    8.2       The Elephant Man (1980)
5    8.3      Full Metal Jacket (1987)
6    8.1              Gone Girl (2014)
7    8.3          Batman Begins (2005)
8    8.2  Judgment at Nuremberg (1961)
9    8.0       Relatos salvajes (2014)
10   8.1  It Happened One Night (1934)

4. How to rename one or more columns?

In [39]:
new_df_1 = df_1.rename(columns={'Votes':'Total Votes','Title':'Movie Title'})
new_df_1.head()

Total Votes  Rank                 Movie Title  Year  Decade
1       132823   8.3  Singin' in the Rain (1952)  1952    1950
2        74178   8.3        All About Eve (1950)  1950    1950
3       635139   8.6                 Léon (1994)  1994    1990
4       145514   8.2     The Elephant Man (1980)  1980    1980
5       425461   8.3    Full Metal Jacket (1987)  1987    1980

5. How to get column names in a list?

In [40]:
df_1.columns.tolist()

['Votes', 'Rank', 'Title', 'Year', 'Decade']

6. How to get the frequency of values in a series?

In [41]:
df_1['Rank'].value_counts()

8.1    53
8.0    50
8.3    38
8.2    34
8.5    24
8.4    21
8.6     9
8.7     9
8.9     6
8.8     2
9.2     2
9.0     1
Name: Rank, dtype: int64

In [42]:
df_1['Decade'].value_counts()[1940] 

14

7. How to reset an index to an existing column or another list or array?

In [43]:
new_df_1 = df_1.reset_index(drop=True,inplace=False) # revert back to original indexing
new_df_1.head()

Votes  Rank                       Title  Year  Decade
0  132823   8.3  Singin' in the Rain (1952)  1952    1950
1   74178   8.3        All About Eve (1950)  1950    1950
2  635139   8.6                 Léon (1994)  1994    1990
3  145514   8.2     The Elephant Man (1980)  1980    1980
4  425461   8.3    Full Metal Jacket (1987)  1987    1980

8. How to remove a column?

In [44]:
new_df_1 = df_1.drop(columns = ['Votes', 'Decade']) # not done in place
new_df_1.head()

Rank                       Title  Year
1   8.3  Singin' in the Rain (1952)  1952
2   8.3        All About Eve (1950)  1950
3   8.6                 Léon (1994)  1994
4   8.2     The Elephant Man (1980)  1980
5   8.3    Full Metal Jacket (1987)  1987

In [45]:
new_df_1.set_index('Rank', inplace=True) # setting Rank as new index 
new_df_1.head()

Title  Year
Rank                                  
8.3   Singin' in the Rain (1952)  1952
8.3         All About Eve (1950)  1950
8.6                  Léon (1994)  1994
8.2      The Elephant Man (1980)  1980
8.3     Full Metal Jacket (1987)  1987

10. How to remove rows or columns if they have NaN values?

In [46]:
new_df_1 = df_1.reindex(index=np.arange(1, 255, 2)) 
new_df_1.tail(10)

Votes  Rank                                         Title    Year  \
235    98949.0   8.2                    Det sjunde inseglet (1957)  1957.0   
237    57974.0   8.0                The Night of the Hunter (1955)  1955.0   
239   424957.0   8.1                    Million Dollar Baby (2004)  2004.0   
241    85012.0   8.1                   Strangers on a Train (1951)  1951.0   
243   268905.0   8.4                           Citizen Kane (1941)  1941.0   
245  1078416.0   8.7                           Forrest Gump (1994)  1994.0   
247   167076.0   8.2                               3 Idiots (2009)  2009.0   
249   589477.0   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004.0   
251        NaN   NaN                                           NaN     NaN   
253        NaN   NaN                                           NaN     NaN   

     Decade  
235  1950.0  
237  1950.0  
239  2000.0  
241  1950.0  
243  1940.0  
245  1990.0  
247  2000.0  
249  2000.0  
251     NaN  
253     NaN

In [47]:
new_df_1.dropna(axis=0,inplace=True)
new_df_1.tail(10)

Votes  Rank                                         Title    Year  \
231   151256.0   8.4                               Das Boot (1981)  1981.0   
233   262425.0   8.3                     Mad Max: Fury Road (2015)  2015.0   
235    98949.0   8.2                    Det sjunde inseglet (1957)  1957.0   
237    57974.0   8.0                The Night of the Hunter (1955)  1955.0   
239   424957.0   8.1                    Million Dollar Baby (2004)  2004.0   
241    85012.0   8.1                   Strangers on a Train (1951)  1951.0   
243   268905.0   8.4                           Citizen Kane (1941)  1941.0   
245  1078416.0   8.7                           Forrest Gump (1994)  1994.0   
247   167076.0   8.2                               3 Idiots (2009)  2009.0   
249   589477.0   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004.0   

     Decade  
231  1980.0  
233  2010.0  
235  1950.0  
237  1950.0  
239  2000.0  
241  1950.0  
243  1940.0  
245  1990.0  
247  2000.0  
249  2000.0

11. How to slice a data frame given a condition?

In [48]:
mask_1 = (df_1['Decade'] == 1950)

In [49]:
mask_1

1       True
2       True
3      False
4      False
5      False
       ...  
245    False
246     True
247    False
248    False
249    False
Name: Decade, Length: 249, dtype: bool

In [50]:
mask_2 = df_1['Decade'].isin([1950, 1960])

movies_1950s = df_1[mask_1]
movies_1950s.head()


Votes  Rank                       Title  Year  Decade
1   132823   8.3  Singin' in the Rain (1952)  1952    1950
2    74178   8.3        All About Eve (1950)  1950    1950
12  156432   8.3     Some Like It Hot (1959)  1959    1950
35   56671   8.0          The Killing (1956)  1956    1950
51   87437   8.0        Roman Holiday (1953)  1953    1950

In [51]:
movies_50_60s = df_1[mask_2]
movies_50_60s.head()

Votes  Rank                                      Title  Year  Decade
1   132823   8.3                 Singin' in the Rain (1952)  1952    1950
2    74178   8.3                       All About Eve (1950)  1950    1950
8    37664   8.2               Judgment at Nuremberg (1961)  1961    1960
12  156432   8.3                    Some Like It Hot (1959)  1959    1950
18  134552   8.1  Butch Cassidy and the Sundance Kid (1969)  1969    1960

In [52]:
mask_3 = (mask_1 & (df_1['Rank'] >= 8.5))
best_movies_1950s = df_1[mask_3]
best_movies_1950s

Votes  Rank                        Title  Year  Decade
86   123879   8.5          Sunset Blvd. (1950)  1950    1950
98   206216   8.7  Shichinin no samurai (1954)  1954    1950
105  384187   8.9          12 Angry Men (1957)  1957    1950
217  280432   8.5           Rear Window (1954)  1954    1950

12. How to slice a data frame given names of columns or index values of rows?

In [53]:
df_1.head()

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [54]:
df_1.iat[1, 2]

'All About Eve (1950)'

In [55]:
df_1.at[4, 'Title']

'The Elephant Man (1980)'

In [56]:
df_1.loc[[1,3,5], ['Rank', 'Title']]

Rank                       Title
1   8.3  Singin' in the Rain (1952)
3   8.6                 Léon (1994)
5   8.3    Full Metal Jacket (1987)

In [57]:
df_1.iloc[[1,3],[2,3]]

Title  Year
2     All About Eve (1950)  1950
4  The Elephant Man (1980)  1980

13. How to iterate over rows?

In [58]:
total_votes = 0
for i,row in df_1.iterrows():
    total_votes += row['Votes']

formatted_total = "{:,}".format(total_votes)
print(formatted_total) 

86,178,431


14. How to sort by a column?

In [59]:
df_1.sort_values(by=['Year', 'Rank'], ascending=True).head(10)

Votes  Rank                                Title  Year  Decade
173   55784   8.3                       The Kid (1921)  1921    1920
205   58506   8.2                 The Gold Rush (1925)  1925    1920
146   46332   8.2                   The General (1926)  1926    1920
49    98794   8.3                    Metropolis (1927)  1927    1920
216   92375   8.5                   City Lights (1931)  1931    1930
10    56842   8.1         It Happened One Night (1934)  1934    1930
212  121668   8.5                  Modern Times (1936)  1936    1930
101  259235   8.1              The Wizard of Oz (1939)  1939    1930
188  192791   8.1            Gone with the Wind (1939)  1939    1930
17    69510   8.2  Mr. Smith Goes to Washington (1939)  1939    1930

15. How to apply a function to each element to a series?

In [60]:
def reformat_votes(v):
    return v / 1000

df_1['Votes'].apply(reformat_votes).head()

1    132.823
2     74.178
3    635.139
4    145.514
5    425.461
Name: Votes, dtype: float64

In [61]:
def votes_per_rank(row):
    return row['Votes'] / row['Rank']

df_1[['Votes', 'Rank']].apply(votes_per_rank, axis=1).head()

1    16002.771084
2     8937.108434
3    73853.372093
4    17745.609756
5    51260.361446
dtype: float64

16. How to apply a function to all elements in a data frame?

In [62]:
df_3

Joe  Ben  Ann
0  6.0  7.5  8.0
1  0.0  1.0  2.0
2  4.0  2.0  6.0

In [63]:
def multiply_by_10(val):
    return val * 10

new_df_3 = df_3.applymap(multiply_by_10)
new_df_3

Joe   Ben   Ann
0  60.0  75.0  80.0
1   0.0  10.0  20.0
2  40.0  20.0  60.0

18. How to group-by column values and aggregate over another column or apply a function to it?

In [64]:
df_1.groupby(['Decade']).agg({'Rank':'mean'})

Rank
Decade          
1920    8.250000
1930    8.250000
1940    8.257143
1950    8.233333
1960    8.231818
1970    8.309524
1980    8.241935
1990    8.357143
2000    8.260000
2010    8.200000

20. How to concatenate two data frames?

In [67]:
mask_4 = df_1['Year'].isin([1925, 1935, 1945, 1955, 1965])
movies_on_the_fives = df_1[mask_4]
movies_on_the_fives

Votes  Rank                              Title  Year  Decade
119   36725   8.1             Les diaboliques (1955)  1955    1950
153  135556   8.3  Per qualche dollaro in più (1965)  1965    1960
205   58506   8.2               The Gold Rush (1925)  1925    1920
237   57974   8.0     The Night of the Hunter (1955)  1955    1950

In [68]:
mask_5 = (df_1['Rank'] == 8.8)
movies_8_8 = df_1[mask_5]
movies_8_8

Votes  Rank                                              Title  Year  \
87   1177098   8.8                                  Fight Club (1999)  1999   
178  1099087   8.8  The Lord of the Rings: The Fellowship of the R...  2001   

     Decade  
87     1990  
178    2000

What are some useful things you can you do with numpy and pandas?

Why would those useful things be helpful in data analysis?

What challenges did you have in following the examples?